[package]
name = "embed"
version = "0.1.0"
authors = ["rei0101b <rei0101b@gmail.com>"]
edition = "2018"
crate-type = ["dylib"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


